###################################################################
#                                                                 #
#                            Negativity                           #
#                      AntiCheat by Elikill58                     #
#                                                                 #
#              If you have a problem or a suggestion,             #
#                    You can contact me on:                       #
#                  - Discord: @Elikill58#0743                     #
#       - my Discord server: https://discord.gg/KHRVTX2           #
#               - Mail: arpetzouille@gmail.com                    #
#                   - SpigotMC: Elikill58                         #
#                  - Minecraft.fr: Elikill                        #
#                                                                 #
###################################################################

log_alerts: true
log_alerts_in_console: true
tps_alert_stop: 19 # if you get less TPS then this value, all alert will be disabled

commands:
  # Options to enable or disable commands
  # Manage /nreport (Alias: /report)
  report: true
  # Manage Mod command :
  # Manage /nkick (Alias: /kick)
  kick: true
  # Manage /nmod (Alias: /mod)
  mod: true
  # Manage /nlang (Alias: /lang)
  lang: true

# The time between 2 /report
# in milliseconds
# -1 to disable
time_between_report: 1000

Database:
  isActive: false
  # To get the information. We use the player uuid to get the information.
  # We get only what you write. We never add or remove something.
  # We don't save your private information about your database
  url: "127.0.0.1/myDb"
  user: root
  password: "myPassword"
  type: "mysql"

inventory:
  alerts:
    no_started_verif_cheat: false # Don't see if the player isn't analyse for this cheat
    only_cheat_active: true # The cheat with an active detection
  inv_freeze_active: true

# Bypass when you add effects
#
items:
  #ITEM_NAME:
  # when: WHEN_DISABLE_DETECTION
  # cheats: CHEATS_DETECTION_DISABLED (it's the ID of the cheats like fly, speed)
  #
  # when available:
  # always : disable when the player get it in their hand
  # right_click : disable when the player right click
  # left_click : disable when the player left click
  # looking : disable when the player is looking a specific type
  # below : disable according to the block below the player
  #
  COMPASS:
    when: always
    cheats: speed,fly

# Configuration of the permissions subsystem. For more information
# see https://github.com/Elikill58/Negativity/wiki/Permissions
Permissions:
  # The checker indicates if a player has a specific permission.
  # By default only 'platform' is available
  checker: platform
  check:
    default: "negativity.check"
  showAlert:
    default: "negativity.alert"
  showReport:
    default: "negativity.seereport"
  verif:
    default: "negativity.verif"
  manageCheat:
    default: "negativity.managecheat"
  reload:
    default: "negativity.reload"
  report_wait:
    default: "negativity.reportwait"
  report:
    default: "negativity.report"
  ban:
    default: "negativity.ban"
  unban:
    default: "negativity.unban"
  mod:
    default: "negativity.mod"
  lang:
    default: "negativity.lang"
  bypass:
    active: false
    ban:
      # Bypass ban (auto and /nban)
      default: "negativity.bypass.ban"
    all:
      default: "negativity.bypass.all"
    forcefield:
      default: "negativity.bypass.forcefield"
    fastplace:
      default: "negativity.bypass.fastplace"
    speed:
      default: "negativity.bypass.speed"
    autoclick:
      default: "negativity.bypass.autoclick"
    fly:
      default: "negativity.bypass.fly"
    antipotion:
      default: "negativity.bypass.antipotion"
    fasteat:
      default: "negativity.bypass.fasteat"
    regen:
      default: "negativity.bypass.regen"
    antiknockback:
      default: "negativity.bypass.antiknockback"
    jesus:
      default: "negativity.bypass.jesus"
    nofall:
      default: "negativity.bypass.nofall"
    blink:
      default: "negativity.bypass.blink"
    spider:
      default: "negativity.bypass.spider"
    fastbow:
      default: "negativity.bypass.fastbow"
    scaffold:
      default: "negativity.bypass.scaffold"
    step:
      default: "negativity.bypass.step"
    noslowdown:
      default: "negativity.bypass.noslowdown"
    fastladder:
      default: "negativity.bypass.fastladder"
    phase:
      default: "negativity.bypass.phase"
    autosteal:
      default: "negativity.bypass.autosteal"
    nuker:
      default: "negativity.bypass.nuker"
    airjump:
      default: "negativity.bypass.airjump"
    chat:
      default: "negativity.bypass.chat"
    noweb:
      default: "negativity.bypass.noweb"
    critical:
      default: "negativity.bypass.critical"
    inventorymove:
      default: "negativity.bypass.inventorymove"
    faststairs:
      default: "negativity.bypass.faststairs"
    nopitchlimit:
      default: "negativity.bypass.nopitchlimit"
    timer:
      default: "negativity.bypass.timer"

Translation:
  active: false # enable or disable the translation
  lang_available:
  - ar_EG
  - cs_CZ
  - de_DE
  - en_US
  - es_ES
  - fr_FR
  - hu_HU
  - it_IT
  - nl_NL
  - no_NO
  - pl_PL
  - pt_BR
  - ro_RO
  - ru_RU
  - sq_SQ
  - sv_SV
  - vi_VN
  - zh_CN
  default: en_US
  # The provider used to get translated messages, useful if you want to customize the way Negativity gets its messages.
  # The only one available out-of-the-box is "platform".
  provider: platform

report:
  spam:
    # Name of report (which is also used as reason)
    name: "&6Spam/Link"
    # the material in inventory
    material: YELLOW_BANNER
    # the slot of item in inventory
    slot: 0
    # the message sent to player when report player
    message: "&6%name% &ahave been reported for %reason%"
    # "permission" is not necessary. If you don't set it, everyone will be able to use it.
  insult:
    name: "&cInsult"
    material: RED_BANNER
    slot: 1
    message: "&6%name% &ahave been reported for %reason%"
    permission: "negativity.report.insult"
  racism:
    name: "&cRacism"
    material: RED_BANNER
    slot: 2
    message: "&6%name% &ahave been reported for %reason%"
    permission: "negativity.report.racism"
  high_ping:
    name: "&4High ping"
    material: BLACK_BANNER
    slot: 9
    message: "&6%name% &ahave been reported for %reason%"
    permission: "negativity.report.ping"
  wrong_name:
    name: "&4Wrong name"
    material: BLACK_BANNER
    slot: 10
    message: "&6%name% &ahave been reported for %reason%"
    permission: "negativity.report.name"
  cheat:
    name: "&4Cheat"
    material: BLACK_BANNER
    slot: 11
    message: "&6%name% &ahave been reported for %reason%"
    permission: "negativity.report.cheat"


kicks:
  spam:
    # Name of report (which is also used as reason)
    name: "&6Spam/Link"
    # the material in inventory
    material: YELLOW_BANNER
    # the slot of item in inventory
    slot: 0
    # the message sent to player which use the inventory
    message: "&6%name% &ahave been kicked for %reason%"
    # the command to run when mod click on the item
    command: "nkick %name% Spam"
    # "permission" is not necessary. If you don't set it, everyone will be able to use it.
  insult:
    name: "&cInsult"
    material: ORANGE_BANNER
    slot: 1
    message: "&6%name% &ahave been kicked for %reason%"
    command: "nkick %name% Insult"
    permission: "negativity.report.insult"
  invalid_name:
    name: "&cInvalid Name"
    material: RED_BANNER
    slot: 2
    message: "&6%name% &ahave been kicked for %reason%"
    command: "nkick %name% Invalid Name"
    permission: "negativity.report.insult"

alert:
  show:
    # Available type :
    # instant: instantly send alert
    # time: the value (in milliseconds) correspond to the time between 2 alerts. Use '-1' to send message instantly
    # amount: the value is the amount of required alert of one cheat to alert
    type: "time"
    # The value according to the type.
    value: 1000
  
  # To run command when someone get alert
  command:
    active: false
    # Reliability need to run command
    reliability_need: 80
    # Available arguments:
    # %name% : Name of player who cheat
    # %uuid% : UUID of player who cheat
    # %report_type% : Type of detected cheat (Know if Negativity consider it as Warning or Violation)
    # %cheat_key% : Cheat key (like "nofall") : You cannot edit it
    # %cheat_name% : Cheat name (like "NoFall") : You can edit it just below
    # %reliability% : Reliability of the alert
    run:
    - "mycommand %name% %cheat_key% %reliability%"


# Accounts hold player-specific data of the plugin, like their language and alerts count.
accounts:
  storage:
    # The ID of the storage to use.
    #
    # The following are available out-of-the-box:
    # - file : stored in files under ./plugins/Negativity/user/
    # - database : uses a database
    # Defaults to "file"
    id: "file"

# A verification is used to monitor a player's activity.
verif:
  # The default duration of a verification, in ticks (20 ticks = 1 second)
  time: 200
  # If true, mutes alerts a player generates when it is being verified
  # Alerts for a specific cheat can be forcibly muted by setting cheats.<cheat>.check_in_verif to false
  disable_alert_on_verif: false

  storage:
    # The ID of the storage to use.
    #
    # The following are available out-of-the-box:
    # - file : stored in files under ./plugins/Negativity/verif/
    # - database : uses a database
    # Defaults to "file"
    id: "file"

region-bypass:
  enabled: false
  1:
    # You need WorldGuard for the region
    regions:
    - "spawn"
    # Default worlds names (or Multiverse names)
    worlds:
    - "world_the_end"
    # the cheats keys
    cheats:
    - "fly"

# Manage webhook
webhooks:
  enable: false
  hook:
    discord-example:
      type: "discord"
      # register the webhook URL used by Negativity
      url: "https://discord.com/api/webhooks/theRestOfDiscordUrl"
      # Configure messages presentation
      # If you don't set one of them, it will get the default configuration
      #
      # Placeholders available everywhere :
      # %name% : Name of the player which procude the message
      # %uuid% : UUID of the player which procude the message
      # %ip% : IP of the player which produce the message
      # %date% : Date when the player procude the message
      # %sender% : The sender of the message (such as banner or reporter)
      # 
      messages:
        # Configure discord webhook message for ban.
        #
        # Placeholders available :
        # %cheat% : the cheat name
        # %amount% : Amount of alert made by player
        # %reliability% : Reliability of the cheat
        alert:
          enabled: true
          # The name which will send the message
          username: "Negativity"
          # The content of the message
          content: ""
          # The URL of the message avatar
          avatar_url: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
          # Now let's configure embed message (the section with black background)
          embed:
            # Color of the embed (used with the line on the left)
            color: "green"
            # The embed title
            title: "Alert"
            # Main description
            description: "%name% seems to use %cheat% %amount%x (Reliability: %reliability%)"
            # All fields.
            # There is 3 fields per line MAX.
            # Else, they will automatically be on the next line.
            fields:
              1:
                # The key which will be at top of field (and bold)
                key: "Player name"
                # The value of the field
                value: "%name%"
                # If the field is inline
                inline: true
              2:
                key: "Player UUID"
                value: "%uuid%"
                inline: true
            # Thumbnail of the message
            thumbnail: "https://kryptongta.com/images/kryptonlogo.png"
            # The footer of the message
            footer:
              name: "Negativity - %date%"
              link: "https://kryptongta.com/images/kryptonlogodark.png"
            # Author details of the message
            author:
              name: "Negativity"
              link: "https://github.com/Elikill58/Negativity"
              icon: "https://kryptongta.com/images/kryptonlogowide.png"
        # Configure discord webhook message for ban.
        #
        # Placeholders available :
        # %name% : Name of the banned player
        # %uuid% : UUID of the banned player
        # %date% : Date when the player have been banned
        ban:
          enabled: true
          # The name which will send the message
          username: "Negativity"
          # The content of the message
          content: ""
          # The URL of the message avatar
          avatar_url: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
          # Now let's configure embed message (the section with black background)
          embed:
            # Color of the embed (used with the line on the left)
            color: "red"
            # The embed title
            title: "Ban"
            # Main description
            description: "%name% have been banned by %sender% for %reason%"
            # All fields.
            # There is 3 fields per line MAX.
            # Else, they will automatically be on the next line.
            fields:
              1:
                # The key which will be at top of field (and bold)
                key: "Player name"
                # The value of the field
                value: "%name%"
                # If the field is inline
                inline: true
              2:
                key: "Player UUID"
                value: "%uuid%"
                inline: true
            # Thumbnail of the message
            thumbnail: "https://kryptongta.com/images/kryptonlogo.png"
            # The footer of the message
            footer:
              name: "Negativity - %date%"
              link: "https://kryptongta.com/images/kryptonlogodark.png"
            # Author details of the message
            author:
              name: "Negativity"
              link: "https://github.com/Elikill58/Negativity"
              icon: "https://kryptongta.com/images/kryptonlogowide.png"
        # Configure discord webhook message for ban.
        #
        # Placeholders available :
        # %reason% : Name of the banned player
        kick:
          enabled: true
          # The name which will send the message
          username: "Negativity"
          # The content of the message
          content: ""
          # The URL of the message avatar
          avatar_url: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
          # Now let's configure embed message (the section with black background)
          embed:
            # Color of the embed (used with the line on the left)
            color: "blue"
            # The embed title
            title: "Kick"
            # Main description
            description: "%name% have been kicked by %sender% for %reason%"
            # All fields.
            # There is 3 fields per line MAX.
            # Else, they will automatically be on the next line.
            fields:
              1:
                # The key which will be at top of field (and bold)
                key: "Player name"
                # The value of the field
                value: "%name%"
                # If the field is inline
                inline: true
              2:
                key: "Player UUID"
                value: "%uuid%"
                inline: true
            # Thumbnail of the message
            thumbnail: "https://kryptongta.com/images/kryptonlogo.png"
            # The footer of the message
            footer:
              name: "Negativity - %date%"
              link: "https://kryptongta.com/images/kryptonlogodark.png"
            # Author details of the message
            author:
              name: "Negativity"
              link: "https://github.com/Elikill58/Negativity"
              icon: "https://kryptongta.com/images/kryptonlogowide.png"
        # Configure discord webhook message for ban.
        #
        # Placeholders available :
        # %reason% : Name of the banned player
        report:
          enabled: true
          # The name which will send the message
          username: "Negativity"
          # The content of the message
          content: ""
          # The URL of the message avatar
          avatar_url: "https://www.spigotmc.org/data/resource_icons/86/86874.jpg"
          # Now let's configure embed message (the section with black background)
          embed:
            # Color of the embed (used with the line on the left)
            color: "red"
            # The embed title
            title: "Report"
            # Main description
            description: "%name% have been reported by %sender% for %reason%"
            # All fields.
            # There is 3 fields per line MAX.
            # Else, they will automatically be on the next line.
            fields:
              1:
                # The key which will be at top of field (and bold)
                key: "Player name"
                # The value of the field
                value: "%name%"
                # If the field is inline
                inline: true
              2:
                key: "Player UUID"
                value: "%uuid%"
                inline: true
            # Thumbnail of the message
            thumbnail: "https://kryptongta.com/images/kryptonlogo.png"
            # The footer of the message
            footer:
              name: "Negativity - %date%"
              link: "https://kryptongta.com/images/kryptonlogodark.png"
            # Author details of the message
            author:
              name: "Negativity"
              link: "https://github.com/Elikill58/Negativity"
              icon: "https://kryptongta.com/images/kryptonlogowide.png"

    discord-another-example:
      type: "discord"
      url: "https://discord.com/api/webhooks/theRestOfSecondDiscordUrl"